version: '3.8'

services:
  jupyter-notebook:
    image: jupyter/base-notebook
    container_name: jupyter-notebook
    ports:
      - "8888:8888"  
    volumes:
      - ./notebook:/home/jovyan  
    environment:
      - JUPYTER_TOKEN=password