version: '3.8'

services:
  platform-local-metastore:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: platform-local-metastore
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "${SQLSERVER_PORT}:${SQLSERVER_PORT}"
    volumes:
      - sql-data:/var/opt/mssql


  # platform-local-metastore:
  #   image: postgres:latest
  #   container_name: platform-local-metastore
  #   environment:
  #     - POSTGRES_USER=sa
  #     - POSTGRES_PASSWORD=${SA_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #   ports:
  #     - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  #   # volumes:
  #   #   - pg-data:/var/lib/postgresql/data
    

  sql-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - platform-local-metastore
    volumes:
      - ./platform-local-metastore:/platform-local-metastore
    entrypoint: >
      /bin/bash -c "
      sleep 15 &&
      until /opt/mssql-tools/bin/sqlcmd -S platform-local-metastore -U sa -P ${SA_PASSWORD} -Q 'SELECT 1'; do
        echo 'Waiting for SQL Server to be ready...'
        sleep 5
      done &&
      /opt/mssql-tools/bin/sqlcmd -S platform-local-metastore -U sa -P ${SA_PASSWORD} -i /platform-local-metastore/init.sql"
    
  # sql-init:
  #   image: postgres:latest
  #   container_name: sql-init
  #   depends_on:
  #     - platform-local-metastore
  #   environment:
  #     - POSTGRES_USER=sa
  #     - POSTGRES_PASSWORD=${SA_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #   volumes:
  #     - ./platform-local-metastore:/platform-local-metastore
  #   entrypoint: >
  #     /bin/bash -c "
  #     echo 'Waiting for PostgreSQL to start...' &&
  #     sleep 10 &&
  #     until pg_isready -h platform-local-metastore -U sa; do
  #       echo 'Waiting for PostgreSQL to be ready...'
  #       sleep 5
  #     done &&
  #     echo 'PostgreSQL is ready, running init.sql' &&
  #     PGPASSWORD=${SA_PASSWORD} psql -h platform-local-metastore -U sa -d ${POSTGRES_DB} -f /platform-local-metastore/init.sql &&
  #     echo 'Database initialized successfully!'"


  platform-quality-receiver:
    build:
      context: ./platform-quality-receiver
    container_name: platform-quality-receiver
    environment:
      - DB_URL=${DB_URL}
      - BD_REFRESH_RATE_MS=${BD_REFRESH_RATE_MS}
      - BD_CREDENTIALS_USERNAME=${BD_CREDENTIALS_USERNAME}
      - BD_CREDENTIALS_PASSWORD=${BD_CREDENTIALS_PASSWORD}
      - BD_CREDENTIALS_TENANT=${BD_CREDENTIALS_TENANT}
    ports:
      - "${QUALITY_RECEIVER_PORT}:${QUALITY_RECEIVER_PORT}"
    depends_on:
      - platform-local-metastore
      - sql-init
    entrypoint: >
      /bin/bash -c "
      sleep 15 &&
      until nc -zv platform-local-metastore 1433; do
        echo 'Waiting for SQL Server to be ready...'
        sleep 5
      done &&
      java -jar /app/platform-quality-receiver.jar"
    

  platform-collector:
    #image: otel/opentelemetry-collector-contrib:latest
    image: otel/opentelemetry-collector-contrib:0.117.0
    container_name: platform-collector
    command: ["--config=/etc/platform-collector/config.yaml"]
    volumes:
      - ./platform-collector/config.yaml:/etc/platform-collector/config.yaml
    ports:
      #- "${OTEL_GRPC_PORT}:${OTEL_GRPC_PORT}"
      - "${OTEL_HTTP_PORT}:${OTEL_HTTP_PORT}"
    depends_on:
      - platform-quality-receiver
      - platform-local-metastore
      - sql-init

  # quality-sidecar:
  #   build:
  #     context: ./quality-sidecar
  #   container_name: quality-sidecar
  #   environment:
  #     - ENV=development
  #     - OTEL_METRIC_EXPORT_INTERVAL=${OTEL_METRIC_EXPORT_INTERVAL}
  #     - DATA_PRODUCT_NAME=${DATA_PRODUCT_NAME}
  #     - EXPECTATIONS_JSON_FILE_PATH=${EXPECTATIONS_JSON_FILE_PATH}
  #   depends_on:
  #     - platform-collector

  jupyter:
    build:
      context: .
      dockerfile: notebook/Dockerfile
    volumes:
      #- ./quality-sidecar/qualitysidecar:/home/jovyan/quality/qualitysidecar
      - ./notebook/quality:/home/jovyan/quality
      #- /home/jovyan/.cache:/home/jovyan/.cache  # Usa questa riga per la cache
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=password
    user: root


  forwarder-1:
    build:
      context: ./forwarder
    container_name: forwarder-1
    environment:
      - ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - BLINDATA_FORWARDER_USERNAME=${BLINDATA_FORWARDER_USERNAME}
      - BLINDATA_FORWARDER_PASSWORD=${BLINDATA_FORWARDER_PASSWORD}
      - BLINDATA_TENANT_ID=${BLINDATA_TENANT_ID}
      - SCHEDULE_INTERVAL=${SCHEDULE_INTERVAL}
    ports:
      - "5000:5000"
    depends_on:
      - platform-local-metastore
      - sql-init
    entrypoint: >
      /bin/bash -c "sleep 10 && 
      until nc -zv platform-local-metastore 1433; do 
        echo 'Waiting for SQL Server to be ready...' && 
        sleep 5; 
      done && 
      echo 'SQL Server is ready, starting the service...' && 
      python3 /app/src/main.py"

  # forwarder-2:
  #   build:
  #     context: ./forwarder
  #   container_name: forwarder-2
  #   environment:
  #     - ENV=development
  #     - DATABASE_URL=${DATABASE_URL}
  #     - BLINDATA_FORWARDER_USERNAME=${BLINDATA_FORWARDER_USERNAME}
  #     - BLINDATA_FORWARDER_PASSWORD=${BLINDATA_FORWARDER_PASSWORD}
  #     - BLINDATA_TENANT_ID=${BLINDATA_TENANT_ID}
  #     - SCHEDULE_INTERVAL=${SCHEDULE_INTERVAL}
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #     - platform-local-metastore
  #     - sql-init
  #   entrypoint: >
  #     /bin/bash -c "sleep 10 && 
  #     until nc -zv platform-local-metastore 1433; do 
  #       echo 'Waiting for SQL Server to be ready...' && 
  #       sleep 5; 
  #     done && 
  #     echo 'SQL Server is ready, starting the service...' && 
  #     python3 /app/src/main.py"

volumes:
  sql-data:
    driver: local

