@echo off
echo Stopping and removing previous container...
docker rm -f gx_manage_result

echo Building new Docker image...
docker build -t gx_manage_result .

echo Running the new Docker container and keeping it alive...
docker run -d --name gx_manage_result gx_manage_result /bin/bash -c "python gx_manage_result.py && tail -f /dev/null"

echo Displaying container logs...
docker logs -f gx_manage_result
